// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 裁决 C-1：统一为 feature-spec 集合（删 design 的 click、原型的 transfer/error）
 */
export type AuditType = "connect" | "auth_fail" | "reject" | "screenshot" | "input" | "disconnect" | "command" | "file_transfer";
