// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditType } from "./AuditType";

export type AuditLog = { id: string, session_id: string, ts: bigint, actor_id: string, actor_user_id: string | null, actor_username: string | null, actor_role: string | null, type: AuditType, text: string, };
