// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 清晰度档位:JPEG 编码质量。Standard=q80,High=q88(q≥90 切 4:4:4 体积翻倍,真机已否决)。
 */
export type ClarityTier = "standard" | "high";
