// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuArch } from "./CpuArch";

export type CpuInfo = { model: string, cores: number, arch: CpuArch, };
