// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 光标形状位图(裸 RGBA,base64)。见 Message::CursorUpdate。
 * id = RGBA 像素的 twox-hash 指纹,主控据此缓存去重(同一形状只传一次)。
 * rgba = w*h*4 字节的 base64(未压缩;光标极小且仅形状变化时发,不值得再上 PNG 依赖)。
 */
export type CursorShape = { id: bigint, hotspot_x: number, hotspot_y: number, w: number, h: number, rgba: string, };
