// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuInfo } from "./CpuInfo";
import type { GpuInfo } from "./GpuInfo";
import type { OsInfo } from "./OsInfo";
import type { RamInfo } from "./RamInfo";

export type EndpointInfo = { id: string, name: string, department: string | null, ip: string, mac: string, os: OsInfo, cpu: CpuInfo, ram: RamInfo, gpu: GpuInfo | null, agent_version: string, };
