// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointInfo } from "./EndpointInfo";

/**
 * 推给管理端的精简视图（含在线态 + 信创标签，不含密码）
 */
export type EndpointView = { info: EndpointInfo, online: boolean, last_seen: bigint, xinchuang: string, };
