// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 远端目录中的一个条目（文件或子目录）。
 */
export type FileEntry = { name: string, is_dir: boolean, size: bigint, };
