// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帧率档位:推帧间隔。Smooth=40ms(~25fps),Standard=66ms(~15fps),Saver=125ms(~8fps)。
 */
export type FpsTier = "smooth" | "standard" | "saver";
