// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputEvent = { "kind": "mouse_move", x: number, y: number, } | { "kind": "mouse_button", button: number, down: boolean, } | { "kind": "key", code: string, down: boolean, } | { "kind": "text", text: string, };
