// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 管理员登录日志条目（功能②；server → admin-web，ts-rs 导出）。
 */
export type LoginLogEntry = { id: bigint, ts: bigint, username: string, ip: string | null, user_agent: string | null, success: boolean, reason: string | null, };
