// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointInfo } from "./EndpointInfo";
import type { EndpointView } from "./EndpointView";
import type { InputEvent } from "./InputEvent";
import type { Mode } from "./Mode";
import type { RamInfo } from "./RamInfo";

/**
 * WS 统一消息体；`#[serde(tag="type")]` **内部 tag**——type 在 payload 对象内（非信封顶层），
 * 前端按 `env.payload.type` 判别，Rust 按枚举变体匹配（裁决 W0-3）。
 */
export type Message = { "type": "register", info: EndpointInfo, password: string, } | { "type": "register_ack", id: string, } | { "type": "heartbeat", id: string, ram: RamInfo, } | { "type": "endpoint_list", endpoints: Array<EndpointView>, } | { "type": "connect_request", mode: Mode, target: string, password: string | null, } | { "type": "incoming_control", session_id: string, from: string, mode: Mode, } | { "type": "auth_result", session_id: string, ok: boolean, reason: string | null, } | { "type": "connect_ack", session_id: string, } | { "type": "reject", session_id: string, reason: string, } | { "type": "frame", session_id: string, data: string, w: number, h: number, seq: bigint, } | { "type": "input", session_id: string, event: InputEvent, } | { "type": "screenshot_req", req_id: string, } | { "type": "screenshot_resp", req_id: string, endpoint_id: string, data: string, w: number, h: number, } | { "type": "session_end", session_id: string, };
