// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointInfo } from "./EndpointInfo";
import type { EndpointView } from "./EndpointView";
import type { FileDir } from "./FileDir";
import type { FileEntry } from "./FileEntry";
import type { InputEvent } from "./InputEvent";
import type { Mode } from "./Mode";
import type { QualityMode } from "./QualityMode";
import type { RamInfo } from "./RamInfo";

/**
 * WS 统一消息体；`#[serde(tag="type")]` **内部 tag**——type 在 payload 对象内（非信封顶层），
 * 前端按 `env.payload.type` 判别，Rust 按枚举变体匹配（裁决 W0-3）。
 */
export type Message = { "type": "register", info: EndpointInfo, password: string, } | { "type": "register_ack", id: string, } | { "type": "heartbeat", id: string, ram: RamInfo, } | { "type": "endpoint_list", endpoints: Array<EndpointView>, } | { "type": "connect_request", mode: Mode, target: string, password: string | null, 
/**
 * WEB 强制远程：免被控端同意直连（仅 admin- 发起方有效，server 端硬校验）。
 */
force: boolean, } | { "type": "incoming_control", session_id: string, from: string, mode: Mode, 
/**
 * true=免同意直连（密码正确/强制），被控端跳过弹框直接进被控态；false=弹框等用户同意。
 */
auto_accept: boolean, } | { "type": "auth_result", session_id: string, ok: boolean, reason: string | null, } | { "type": "connect_ack", session_id: string, } | { "type": "reject", session_id: string, reason: string, } | { "type": "frame", session_id: string, data: string, w: number, h: number, seq: bigint, } | { "type": "input", session_id: string, event: InputEvent, } | { "type": "set_quality", session_id: string, mode: QualityMode, } | { "type": "remote_notice", session_id: string, text: string, } | { "type": "clipboard_sync", session_id: string, text: string, } | { "type": "screenshot_req", req_id: string, } | { "type": "screenshot_resp", req_id: string, endpoint_id: string, data: string, w: number, h: number, } | { "type": "session_end", session_id: string, } | { "type": "exec_request", session_id: string, exec_id: string, command: string, timeout_ms: number, } | { "type": "exec_result", session_id: string, exec_id: string, exit_code: number | null, stdout: string, stderr: string, truncated: boolean, duration_ms: number, } | { "type": "file_open", session_id: string, transfer_id: string, name: string, size: bigint, dir: FileDir, 
/**
 * push 下发的目标目录（控制方在远端文件浏览器里选定的当前目录）；
 * None 或非法时被控端回退到固定接收目录 recv_dir。pull 回流时恒为 None。
 */
dest: string | null, } | { "type": "file_chunk", session_id: string, transfer_id: string, seq: bigint, data: string, last: boolean, } | { "type": "file_pull_request", session_id: string, transfer_id: string, path: string, } | { "type": "file_error", session_id: string, transfer_id: string, reason: string, } | { "type": "file_done", session_id: string, transfer_id: string, path: string, } | { "type": "file_list_request", session_id: string, transfer_id: string, path: string, } | { "type": "file_list_resp", session_id: string, transfer_id: string, path: string, entries: Array<FileEntry>, error: string | null, };
