// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画质档位：高清优先（分辨率/质量高、帧率低）/ 流畅优先（分辨率/质量低、帧率高）。
 * 具体的分辨率/质量/帧率参数由被控端 capture 模块按档位决定，协议只传枚举。
 */
export type QualityMode = "high_quality" | "smooth";
