// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分辨率档位:采集缩放上限(fit-within 等比,绝不放大)。Native=不缩放,按被控真实屏发送。
 */
export type ResolutionTier = "r720p" | "r900p" | "r1080p" | "native";
