// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 终态语义（Wave 0 钉死）：status 只记会话**最终结果**——拒因细分（密码错 `auth_fail`
 * vs 被控点拒 `reject`）不进 status，查 `AuditLog.kind`；`Active`=进行中，`Ended`=正常结束，
 * `Rejected`=未建立（含两种拒因）。
 */
export type SessionStatus = "active" | "ended" | "rejected";
